name: morning
on:
  schedule:
  - cron:  '0 0 * * *'

jobs:
  send_message:
    runs-on: ubuntu-latest
    name: send morning to girlfriend

    steps:
    - name: checkout
      uses: actions/checkout@v3
      with:
        ref: master

    - name: sender
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
        architecture: 'x64'
    - run: pip install -r ./requirements.txt && python ./main.py

    env:
      APP_ID: ${{ secrets.APP_ID }}
      APP_SECRET: ${{ secrets.APP_SECRET }}
      TEMPLATE_ID: ${{ secrets.TEMPLATE_ID }}
      USER_ID_1: ${{ secrets.USER_ID_1 }}
      USER_ID_2: ${{ secrets.USER_ID_2 }}
      START_DATE: ${{ secrets.START_DATE }}
      BIRTHDAY_SHE: ${{ secrets.BIRTHDAY_SHE }}
      BIRTHDAY_HE: ${{ secrets.BIRTHDAY_HE }}
      CITY: ${{ secrets.CITY }}
